#!/bin/sh
set -x

# Copy user source to /home/node/usr
cp -Rfpv /tmp/src/* /home/node/usr

# Install user dependencies if they exist
# cd /home/node/usr
# if [ -f package.json ] ; then
#   npm install --only=prod
# fi

