#!/bin/sh
set -x

# Copy user source to ${HOME}/usr
cp -Rfpv /tmp/src/* ${HOME}/usr

# Install user dependencies if they exist
cd ${HOME}/usr
if [ -f package.json ] ; then
  npm install --only=prod
fi

