#!/bin/sh
set -x

# Uncomment for debugging
# ls -l ${HOME}/usr ${HOME}/usr/node_modules ${HOME}/usr/node_modules/is-number ${HOME}/src ${HOME}/src/node_modules ${HOME}/src/node_modules/is-number

cd ${HOME}/src

NODE_PATH=${HOME}/usr:${HOME}/src node .
